name: pytest

on: [push,pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest
    name: pytest
    steps:
    - uses: fylein/python-pytest-github-action@v1
      with:
        args: pip3 install -r requirements.txt && pytest test/unit