name: pytest

on: [push,pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest
    name: pytest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - run: pip install --upgrade pip
    - run: pip install "black<23" mypy==v0.902 pytest
    - run: black --diff --check $(git ls-files '*.py')
    #- run: mypy --strict $(git ls-files '*.py')
    - run: pytest